### ISSUE TITLE
Invalid folding descriptor range

### ISSUE THREAD

**Issue by kaleev** [ArtsiomCh/JDCleanRead#4]
There is a trace diagnosing invalid folding descriptor range.
It might be produced by JDCleanRead plugin. But there is not enough diagnostic information to be sure. Could you please check?

Folding descriptor (34443,34455) for AST: PsiDocToken:DOC_COMMENT_DATA made by CompositeFoldingBuilder[com.intellij.codeInspection.i18n.folding.PropertyFoldingBuilder@3153192, com.intellij.codeInsight.daemon.impl.actions.SuppressWarningsFoldingBuilder@2659c55a, com.intellij.codeInsight.folding.impl.JavaFoldingBuilder@7ad5585f, com.github.artsiomch.jdcr.JdcrFoldingBuilder@4e9bb6f, com.intellij.uiDesigner.binding.GeneratedCodeFoldingBuilder@2e5a93c1, com.android.tools.idea.folding.ResourceFoldingBuilder@46c1e045, com.intellij.spring.folding.CodePropertyPlaceholderFoldingBuilder@16065f62] for Language: JAVA is outside document range, PSI element: PsiDocToken:DOC_COMMENT_DATA, PSI element range: (34442,34455); wrong document for File[PsiJavaFile:Class.java Class.java, Language: JAVA, com.intellij.psi.SingleRootFileViewProvider{myVirtualFile=jar:///usr/lib/jvm/java-1.8.0-openjdk/src.zip!/java/lang/Class.java, content=VirtualFileContent{size=148818}}]; expected DocumentImpl[file:///someUserFile.java]; actual DocumentImpl[jar:///usr/lib/jvm/java-1.8.0-openjdk/src.zip!/java/lang/Class.java]

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:80) VCS
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156) VCS
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.diagnoseIncorrectRange(FoldingUpdate.java:290) VCS
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:246) VCS
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:218) VCS
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:83) VCS
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:67) VCS
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:216) VCS
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:202) VCS
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42) VCS
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52) VCS
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429) VCS
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971) VCS
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422) VCS
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:577) VCS
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:523) VCS
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59) VCS
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421) VCS
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397) VCS
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:158) VCS
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:156) VCS
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395) VCS
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171) VCS
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by kaleev** [comment]
reported in IntelliJ IDEA 2020.1 EAP (201.3803.71)

**Comment by ArtsiomCh** [comment]
Which version of JDCleanRead you've been using? Cause it's not yet compatible with IDEA 2020 and should be disabled if you try to run it under 2020...
Anyway, I just adopted and checked the plugin to 2020 and didn't get any exception. 
As far as I can see from your log, my plugin just mentioned in the list of loaded FoldingBuilders (and it not supposed to be loaded into 2020 at all actually...) but no other evidence which particular FoldingBuilder causes this exception. 
I would report this to JetBrain as it looks to be possibly something wrong on their side. Also, it's still EAP and bugs are expected.

**Comment by kaleev** [comment]
It's a report received in JetBrains from one of our users. There is no information about JDCleanRead version. As I said it might be a problem with some other plug-in, so I just asked to check JDCleanRead compatibility with 2020. Thank you for quick checking!

**Comment by ArtsiomCh** [comment]
Thank you for clarification! 
Let me know if you find any other (possible) issues with my plugin(s).
