### ISSUE TITLE
NullPointerException in addFoldingDescriptor

### ISSUE THREAD

**Issue by Javaru** [ArtsiomCh/JDCleanRead#5]
The following exception occurred. I'm not sure what triggered it as the timestamp on it is from overnight. So some background process must have triggered it. v212.0.1 running on 2021.2.1 Ultimate

```
java.lang.NullPointerException
	at com.github.artsiomch.jdcr.JdcrFoldingBuilder.addFoldingDescriptor(JdcrFoldingBuilder.java:142)
	at com.github.artsiomch.jdcr.JdcrFoldingBuilder.addFoldingDescriptor(JdcrFoldingBuilder.java:133)
	at com.github.artsiomch.jdcr.JdcrFoldingBuilder.checkHtmlTagsAndEscapedChars(JdcrFoldingBuilder.java:119)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.github.artsiomch.jdcr.JdcrFoldingBuilder.buildFoldRegions(JdcrFoldingBuilder.java:45)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:95)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:36)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:88)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:71)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:266)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:232)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:86)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$updateFoldRegions$0(FoldingUpdate.java:75)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:72)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:226)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by ArtsiomCh** [comment]
Sorry for delayed response and Thank you for report!
Looks like a one-time glitch for me. Can't see how `NullPointerException` could happened there...
Will close for now. Let me know if it happened again please.

**Comment by Javaru** [comment]
Hello @ArtsiomCh 

I got the exception again. (It was a couple of days ago, but I did not have a chance to report until now.) Same basic stacktrace. I took a look in the logs. Immediately after the exception was logged at `2022-03-09 14:41:42,017`, the following was also logged. Not sure if it is related to the exception. But either way, likely something you need to look at.

```
2022-03-09 14:41:42,249 [708685884]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.github.artsiomch.jdcr.JdcrAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: com.github.ArtsiomCh.JDCleanRead]' was reported 7960 times 
2022-03-09 14:41:42,249 [708685884]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.github.artsiomch.jdcr.JdcrAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: com.github.ArtsiomCh.JDCleanRead]' was reported 1620 times 
2022-03-09 14:41:42,250 [708685885]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.github.artsiomch.jdcr.JdcrAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: com.github.ArtsiomCh.JDCleanRead]' was reported 7970 times 
2022-03-09 14:41:42,305 [708685940]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.github.artsiomch.jdcr.JdcrAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: com.github.ArtsiomCh.JDCleanRead]' was reported 7980 times 
2022-03-09 14:41:42,306 [708685941]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class com.github.artsiomch.jdcr.JdcrAnnotator) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: com.github.ArtsiomCh.JDCleanRead]' was reported 7990 times 
```


> Can't see how NullPointerException could happened there...

I took a look at your code as an "extra set of eyes" check, and I concur. My only thoughts (off the top of my head without looking at the code in much detail is) 1) could there be some sort of threading issue that causes the `foldingDescriptors` to be emptied immediately after the `!isEmpty` check and before the `peek()` call such that `peek()` ends up returning `null` or 2) is there maybe a bug in `FoldingDescriptor` and `getRange()` is breaking its `@NotNull` contract or 3) is something causing the `TextRange` to be null when the `FoldingDescriptor` is created/constructed. Again, just some quick thoughts off the top of my head.

Let me know if there is any additional info I can provide you.

Version info with the latest occurrence.

```
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 27, 2022
Non-Bundled Plugins:
     com.github.ArtsiomCh.JDCleanRead (212.0.1)
     . . .

```
