### ISSUE TITLE
com.intellij.diagnostic.PluginException Caused by: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Javaru** [ArtsiomCh/JDCleanRead#7]
Not sure what action may have triggered this as I did not notice it until later in the day. It happened tywice with same stacktrace, just a slightly different message:

### Occurrence 1 Message
com.intellij.diagnostic.PluginException: Folding descriptor (24199,24206) for AST: PsiDocToken:DOC_COMMENT_DATA, containing PSI element PsiDocToken:DOC_COMMENT_DATA of class com.intellij.psi.impl.source.javadoc.PsiDocTokenImpl, provided by com.github.artsiomch.jdcr.JdcrFoldingBuilder@6acf0aa (class com.github.artsiomch.jdcr.JdcrFoldingBuilder) must belong to the file PsiJavaFile:AuthenticationFilter.java, but got: PsiJavaFile:MySqlAuthorizationDao.java [Plugin: com.github.ArtsiomCh.JDCleanRead]

### Occurrence 2 Message

com.intellij.diagnostic.PluginException: Folding descriptor (892,899) for AST: PsiDocToken:DOC_COMMENT_DATA, containing PSI element PsiDocToken:DOC_COMMENT_DATA of class com.intellij.psi.impl.source.javadoc.PsiDocTokenImpl, provided by com.github.artsiomch.jdcr.JdcrFoldingBuilder@6acf0aa (class com.github.artsiomch.jdcr.JdcrFoldingBuilder) must belong to the file PsiJavaFile:MySqlAuthorizationDao.java, but got: PsiJavaFile:AuthenticationFilter.java [Plugin: com.github.ArtsiomCh.JDCleanRead]

### Stacktrace 
```
com.intellij.diagnostic.PluginException: Folding descriptor (24199,24206) for AST: PsiDocToken:DOC_COMMENT_DATA, containing PSI element PsiDocToken:DOC_COMMENT_DATA of class com.intellij.psi.impl.source.javadoc.PsiDocTokenImpl, provided by com.github.artsiomch.jdcr.JdcrFoldingBuilder@6acf0aa (class com.github.artsiomch.jdcr.JdcrFoldingBuilder) must belong to the file PsiJavaFile:AuthenticationFilter.java, but got: PsiJavaFile:MySqlAuthorizationDao.java [Plugin: com.github.ArtsiomCh.JDCleanRead]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:99)
	at com.intellij.lang.folding.CompositeFoldingBuilder.assertSameFile(CompositeFoldingBuilder.java:61)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:44)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:74)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:272)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:240)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:138)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2$1$1.invoke(PsiAwareTextEditorImpl.kt:78)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2$1$1.invoke(PsiAwareTextEditorImpl.kt:77)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:386)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator(coroutines.kt:374)
	at com.intellij.openapi.progress.CoroutinesKt.contextToIndicator(coroutines.kt:347)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextToIndicator(coroutines.kt:340)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2.invoke(PsiAwareTextEditorImpl.kt:77)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2.invoke(PsiAwareTextEditorImpl.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground$suspendImpl(PsiAwareTextEditorImpl.kt:74)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.kt)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$start$continuationDeferred$1.invokeSuspend(AsyncEditorLoader.kt:116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: Folding descriptor (24199,24206) for AST: PsiDocToken:DOC_COMMENT_DATA, containing PSI element PsiDocToken:DOC_COMMENT_DATA of class com.intellij.psi.impl.source.javadoc.PsiDocTokenImpl, provided by com.github.artsiomch.jdcr.JdcrFoldingBuilder@6acf0aa (class com.github.artsiomch.jdcr.JdcrFoldingBuilder) must belong to the file PsiJavaFile:AuthenticationFilter.java, but got: PsiJavaFile:MySqlAuthorizationDao.java
	at com.intellij.lang.folding.CompositeFoldingBuilder.assertSameFile(CompositeFoldingBuilder.java:63)
	... 59 more
```

**Comment by Javaru** [comment]
FYI: This occurs repeatedly and consistently on IntelliJ IDEA v2023.2. (i.e. dozens of times a day). It's at the point that I've had to disable the JavaDoc Clean Read Plugin.

**Comment by ArtsiomCh** [comment]
Hi, @Javaru 
Thanks for reporting! Indeed that could happened in some rare cases if you open files very fast ;)
Please try [232.1.0-beta1](https://github.com/ArtsiomCh/JDCleanRead/files/12323445/JDCleanRead.zip)
 version with fix (make sure you're installing .zip file and not unpacked .jar without dependencies) and let me know please if issue is gone. 
PS Use "install plugin from disk" for that:
![image](https://github.com/ArtsiomCh/JDCleanRead/assets/14268320/c03830df-9428-472c-89db-163abc1cde2c)

**Comment by Javaru** [comment]
@ArtsiomCh Sorry, I missed the email informing of your comment, and am just seeing it now. I see you've release 232.1.0 in the marketplace. I've installed and enable it, and will let you know if I see the issue again.
